"""Module that provides constants."""
MAX_LENGTH_COUNTRY = 100
MAX_LENGTH_REGION = 100
MAX_LENGTH_CITY = 100

MAX_LENGTH_DESCRIPTION = 500
MAX_LENGTH_COOL_FACTS = 100
MAX_LENGTH_WW_DISTRIBUTION = 100
MAX_LENGTH_PROTECT = 100

CORDS_MAX_DIGITS = 16
CORDS_MAX_DECIMAL = 14

BUCKET_NAME = 'images'

MAX_LENGTH_INSTITUTE = 50
MAX_LENGTH_PROJECT = 50
MAX_LENGTH_LABEL_NAME = 50
MAX_LENGTH_MORPH_FEATURES = 50

MAN_TAXON_LENGTH = 30

MAX_LENGTH_AUTHOR = 50
MAX_LENGTH_GEO_AUTHOR = 50
MAX_LENGTH_RUS_NAME = 100
MAX_LENGTH_TAXONOMY_COL = 100

MAX_POSITIVE_DEGREE = 90
MAX_NEGATIVE_DEGREE = -90
